[package]
name = "mlvillage"
version = "0.1.0"

[dependencies]
starknet = "2.5.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag= "v0.9.0" }

[[target.starknet-contract]]
sierra = true
# casm = true
# sierra-text=true
# casm-add-pythonic-hints =true